# #cloud smith assesment 2 actions file below
# name: CI/CD Workflow

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.x'

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install setuptools wheel

#     - name: Build package
#       run: |
#         python setup.py sdist bdist_wheel

#     - name: Upload package to Cloudsmith
#       uses: cloudsmith-io/action@master
#       with:
#         api-key: {{ secrets.CLOUDSMITH_API_KEY }}
#         command: "push"
#         format: "python"
#         owner: "interview-mohit-yadav"
#         repo: "interview-mohit-yadav"
#         republish: "true"
#         file: "dist/*"




# name: CI/CD Workflow

# on:
#   push:
#     branches:
#       - main

# permissions:
#   id-token: write  # Required for OIDC authentication
#   contents: read   # Default read permission

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.x'

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install setuptools wheel

#     - name: Build package
#       run: |
#         python setup.py sdist bdist_wheel

#     - name: Upload package to Cloudsmith
#       uses: cloudsmith-io/action@master
#       with:
#         token: {{ secrets.GITHUB_TOKEN }}  # Placeholder; use the correct token output
#         command: "push"
#         format: "python"
#         owner: "interview-mohit-yadav"
#         repo: "interview-mohit-yadav"
#         republish: "true"
#         file: "dist/*"


name: CI/CD Workflow

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read   # Required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Retrieve OIDC Token
      id: oidc-token
      run: |
        echo "TOKEN=${{ steps.oidc-token.outputs.id_token }}" >> $GITHUB_ENV

    - name: Upload package to Cloudsmith
      uses: cloudsmith-io/action@master
      with:
        token: ${{ env.TOKEN }}  # Use the OIDC token dynamically generated
        command: "push"
        format: "python"
        owner: "interview-mohit-yadav"  # Your Cloudsmith organization name
        repo: "interview-mohit-yadav"  # The repository name associated with your service account
        republish: "true"
        file: "dist/*"

    - name: Debug Output
      run: |
        echo "OIDC Token: ${{ env.TOKEN }}"

