name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Upload package to Cloudsmith
      uses: cloudsmith-io/action@master
      with:
        api_key: ${{ secrets.CLOUDSMITH_API_KEY }}
        owner: 'mohit-yadav'    # Adjusted to lowercase for consistency with Cloudsmith conventions
        repo: 'interview-mohit-yadav'
        format: 'python'          # Changed 'python' to 'pypi' to match Cloudsmith's expected format for Python packages
        package: 'dist/*'
